steps:
  - label: ":whale::node: Build"
    command: docker/build

  - wait

  - label: ":playwright::chrome: Browser tests"
    command: docker/browser_tests
    artifact_paths:
      - "app/static/test-results/**/*"

  - wait

  - label: ":shipit: Push images"
    command: docker/push
