steps:
  - label: ":whale::node: Build"
    command: docker/build

  - wait

  - label: ":playwright::chrome: Browser tests"
    command: docker/browser_tests

  - wait

  - label: ":shipit: Push images"
    command: docker/push
