#!/usr/bin/env bash
set -eux

function remove_containers() {
    docker kill odin.api wodin wodin-redis wodin-playwright 2>/dev/null || /bin/true
}

function cleanup() {
    set +x
    remove_containers
}
trap cleanup EXIT

ROOT=$(dirname $(dirname $0))

ROOT=$PWD
. $ROOT/docker/common

remove_containers

## all deps
./scripts/run-dependencies.sh

## main app
docker pull $TAG_SHA
docker run --rm -d --name wodin --network=host $TAG_SHA /wodin/config

## run the tests
docker run --rm --name wodin-playwright --network=host \
       -w /wodin/app/static \
       --entrypoint /wodin/docker/run_browser_tests \
       $TAG_SHA
