#!/usr/bin/env bash
set -eux

if [ ! -d tests/e2e ]; then
    echo "Expected this script to be run from app/static"
    exit 1
fi

npm install @playwright/test
npx playwright install
npx playwright install-deps
npm run e2e-test
