#!/usr/bin/env bash
if [ "$#" -eq 0 ]; then
    CONFIG=/wodin/config
elif [ "$#" -eq 1 ]; then
    CONFIG=$1
if [ "$#" -ne 1 ]; then
    echo "Usage wodin [<config.json>]"
    exit 1
fi
node /wodin/app/server/dist/server/server.js --config $CONFIG
