#!/usr/bin/env bash
if [ "$#" -ne 1 ]; then
    echo "Usage wodin <config.json>"
    exit 1
fi
CONFIG=$1
# npm run serve --prefix=/wodin/app/server --config $CONFIG
node /wodin/app/server/dist/server/server.js --config $CONFIG
