name: build

on: [push]

env:
  TAG_GHCR: mrc-ide/wodin

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: ci-env
        uses: ./.github/actions/ci-env-and-ghcr-login
        with:
          ghcr-username: ${{ github.actor }}
          ghcr-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checking
        run: |
          GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          curl "https://ghcr.io/v2/mrc-ide/wodin/manifests/mrc-5976" -H "accept: application/vnd.docker.distribution.manifest.v2+json" -H "Authorization: Bearer ${GHCR_TOKEN}"
      
      - name: Build and push docker
        uses: docker/build-push-action@v5
        with:
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{env.TAG_GHCR}}:${{steps.ci-env.outputs.CI_SHA}}
            ghcr.io/${{env.TAG_GHCR}}:${{steps.ci-env.outputs.CI_BRANCH}}
      - name: Smoke test
        run: |
          ./scripts/run-version.sh --app ${{steps.ci-env.outputs.CI_BRANCH}} &
          ./scripts/smoke-test.sh
