name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install -g typescript codecov
      - name: Build
        run: ./scripts/build.sh
      - name: Run dependencies
        run: ./scripts/run-dependencies.sh
      - name: Run server
        run: npm run serve --prefix=app/server &
      - name: Test back end
        run: npm test --prefix=app/server
      - name: Test front end
        run: npm run test:unit --prefix=app/static
      - name: Lint back end
        run: npm run lint --prefix=app/server
      - name: Lint front end
        run: npm run lint --prefix=app/static
      - name: Check versions
        run: npm run genversion --prefix=app/server -- --check-only
      - name: Upload coverage
        run: |
          codecov -f app/static/coverage/*.json
          codecov -f app/server/coverage/*.json
